name: Hillside Marin
favicon: null
layout_spectrum: 0.26885
typography_spectrum: 0.56767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#484443'
    - '#75ade6'
    - '#060b0e'
    - '#7a7a7c'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.80273179220967
  rhythmicContrast: 0.25
purpose: []
