name: Hillside Marin
favicon: null
layout_spectrum: 0.54735
typography_spectrum: 0.56767
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a4b8b9'
    - '#f0d6a5'
    - '#ffffff'
    - '#6c5b3d'
  brandStrength: 0.3125
  lightness: 0.26444984693080187
  saturation: 0.80273179220967
  rhythmicContrast: 0.25
purpose: []
